### ISSUE TITLE
Return raw response in browser?

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/graphiql#107]
Is it possible to hit a URL that doesn't render GraphIQL, but instead returns the raw results of a query in the browser? 

Example: https://tonicdev.io/kevinsuttle/56e19b940b36c911004f9383/branches/master

renders
`hello world`

**Comment by dschafer** [comment]
Yep, and the express-graphql package has this behavior! If you're using that package (which includes graphiql), then you can pass the `raw` GET param to any GraphiQL URL, and the server will output the raw response rather than GraphiQL. The logic to do that is at https://github.com/graphql/express-graphql/blob/470476e2808e938b5a84a2dfb4ff15a4ac765a98/src/index.js#L261, and you can compare the two using the swapi-graphql example deployment with http://graphql-swapi.parseapp.com/graphiql?query={person(personID:1){name,mass}} and http://graphql-swapi.parseapp.com/graphiql?query={person(personID:1){name,mass}}&raw.

Hope this helps!

**Comment by kevinSuttle** [comment]
AWESOME! That worked. All I had to do was add `&raw` to the end of the URL. Thanks so much @dschafer!

**Comment by kevinSuttle** [comment]
Is this the same for `&search`? 

https://github.com/graphql/graphiql/blob/master/example/index.html#L39
