### ISSUE TITLE
Feature request: Add ability to specify custom headers

### ISSUE THREAD

**Issue by eugenehp** [graphql/graphiql#148]
It would be great to have functionality to add custom headers for authorisation purposes within GraphQL.

**Comment by eugenehp** [comment]
I'm working on the PR at the moment.

![screen shot 2016-06-22 at 20 03 38](https://cloud.githubusercontent.com/assets/1857263/16290708/8010ec58-38b4-11e6-8a49-675f95614218.png)

**Comment by asiandrummer** [comment]
Hi @eugenehp - thanks for the suggestion! We have discussed a custom header feature request in the past: #114 for one of the examples. Would it be more plausible for your use case to define a custom `graphQLFetcher` that deals with custom headers?

**Comment by eugenehp** [comment]
Hi @asiandrummer yes, absolutely. I'll take a look into it. I already played with the example directory and got it working. What would be the best way to define custom `graphQLFetcher` to work with the HTTP headers?

![screen shot 2016-06-22 at 20 31 25](https://cloud.githubusercontent.com/assets/1857263/16291787/80aebb62-38bf-11e6-8908-f04b9c3f6a23.png)
<img width="1550" alt="screen shot 2016-06-22 at 20 31 27" src="https://cloud.githubusercontent.com/assets/1857263/16291788/80d5ca54-38bf-11e6-9e04-94f0b9b02e35.png">

**Comment by asiandrummer** [comment]
I think you may have already looked at it, but refer to [this example](https://github.com/graphql/graphiql/blob/master/example/index.html) from the example code we have. It defines a custom `graphQLFetcher` with a set of custom headers.

The main reason why we'd prefer this is because we want `GraphiQL` to be independent of the network configurations. See #96 and #59 for more conversations about this please.

**Comment by eugenehp** [comment]
@asiandrummer Thanks Hyo. I'm moving this [here](https://github.com/graphql/express-graphql/issues/101) so we can have a way to place GraphiQL and custom versions of it as middleware.

**Comment by webmobiles** [comment]
how i can use the middleware to input the headers ? I've tried plugins for chrome and app for mac, and none of them is working ? it's a pity no input headers in the original graphiql, looks dogmatic decision

**Comment by asiandrummer** [comment]
@webmobiles it's difficult to answer your question without knowing which middleware you're talking about and the plugins you've tried/without mentioning them. I heard that GraphiQL for Mac already supports a custom header, but have not seen it/used it myself. 

I think [Lee's comment here](https://github.com/graphql/graphiql/pull/602#issuecomment-331963529), in addition to multiple responses we've given to explain this, best describes why we wouldn't support custom headers in GraphiQL.

**Comment by balthild** [comment]
In many cases, we're using GraphiQL for debugging an API server in development. I think it's required that adding a field to the interface rather than change the behaviour programmatically.
 
1. The GraphiQL is often bundled with the library, for example, [Graphene](https://github.com/graphql-python/flask-graphql) and [Apollo Server](https://github.com/apollographql/apollo-server). We're not able to use a custom fetcher while using such these libraries.
2. For debugging, we often need changing the header frequently than keep a static value. Setting headers on the interface will be much more convenient even if we could customize the fetcher.

**Comment by imolorhe** [comment]
@balthild You can checkout https://github.com/imolorhe/altair as well.

**Comment by balthild** [comment]
@imolorhe Great project!
