### ISSUE TITLE
elegantly prettify input object in graphiql

### ISSUE THREAD

**Issue by wawhal** [graphql/graphiql#1516]
The prettify button puts the input objects in single line. It would be nice if it gets prettified in a prettified JSON structure.

Current prettification:

```graphql
query MyQuery {
  user(where: {id: {_eq: 10}}) {
    id
    name
    age
  }
}
```

Expected prettification:

```graphql
query MyQuery {
  user (
    where: {
      id: {
        _eq: 10
      }
    }
  ) {
    id
    name
    age
  }
}
```

**Comment by FredyC** [comment]
Yea, Prettier can do that, so isn't that like about upgrading dependency? :)

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBHArnATgTwAQCyOAiprnsADpR57oDO2AFAO4AW2cSFAlgCbdgAfTipuARgAMAXwA0efoJFi8UuQoEVlEmfMVbRO9fuGHVM6QEoK1WrX627UAIYBbOI9rOA5h5p5pamkQWRAIAAcYHmh6ZFBnLCwIFgAFBIRYlGcAGxZnHFjQgCMsZzAAazgYAGVwsp4ob2QYLExQthhXbIB1Nh54ejqwOGqM-p4AN36cZHB6QpAGxiwYFNLvV2dkADMcxlCAK3oADwAhUoqq6rc4ABkGuB29uEOT6obvbLhSCHgn7P2IDqWGWs28pXCbFQ2RCQKwDRg3X4MDYyAAHJJQuEkoxuhDZti4MsJo9QhhfnA1hFMiBnPQALRQOBwPgs2FYUToHgctY+Tb-QGMVw8ZqtF4gegfL4-P5IXYA8UwZxFJF8FHIABMoRazh42Q+AGEIK5+SgiQBWWEMOAAFWVmXlgImmAAklBWbBqmB4ZEAILu6owHBfAVwaTSIA

**Comment by acao** [comment]
hey thanks for reporting this! there have been many feature requests for these, so please chime in on one that is already open next time!

because `prettier/standalone` starts at about 500kb addition to the payload. the current size is 720kb. we are not using prettier currently, instead a much lighter and simpler 

so my solution was to load it dynamically, which we are doing in the RFC here:
https://github.com/acao/graphiql/pull/17

so prettier configurations will be configurable in the language service, monaco mode and GraphiQL shortly, please help us review the in progress work!

if you'd like to see this merged, please help review and advance the plugin API effort: https://github.com/graphql/graphiql/issues/983!

**Comment by acao** [comment]
let's move discussion to this proposal: #1517

if y'all are interested and don't mind pulling down that PR and try it out locally, you can give some feedback. it's essentially the same as it works in codesandbox, slightly similar to vscode except you can't configure formatters, there is only one
