### ISSUE TITLE
graphiql@1.0.1 has no commonjs build

### ISSUE THREAD

**Issue by jgillich** [graphql/graphiql#1584]
@acao The graphiql npm package has no commonjs build (no `dist` directory). I get the same issue locally when I run `yarn run build` inside `packages/graphiql`, but it builds fine when I run it from the root. Might be some configuration issue there. :thinking:

**Comment by acao** [comment]
@jgillich good catch, 1.0.2 solves this, i made a mistake publishing!

**Comment by jgillich** [comment]
Yay, thanks!

**Comment by acao** [comment]
when i published 1.0.1, it was my first time publishing from a branch other than master, and i did `lerna publish` instead of our prescribed `yarn lerna-publish` because I was lazy and not paying close enough attention, and accidentally released the 2.0.0 rewrite code as 1.0.1 :fearful: 

if you have any other issues, you'll know where to find me!
