### ISSUE TITLE
GraphiQL depends on require()

### ISSUE THREAD

**Issue by ggascoigne** [graphql/graphiql#1606]
I'm trying to use GraphiQL with snowpack and this highlighted that GraphiQL uses `require` internally.  Now that there's a standard for a browser implementation of dynamic loading, can this be refactored to use dynamic import instead? Having the library be dependent upon webpack or browserify feels like the wrong (or at least an out of date) solution.

**Comment by acao** [comment]
we tried this and unfortunately it caused issues with webpack tree shaking. we can give it another shot for 1.0.0

**Comment by acao** [comment]
this has been a whole rabbit hole because of the codemirror typescript definitions. feel free to create your own version of the PR to get this working:
https://github.com/graphql/graphiql/pull/1610

for the meantime, i need to pivot back to graphiql 2.0.0 plugin api

**Comment by cgarnier** [comment]
Got an issue with  `vite` too. It s working well in `dev` but the build doesnt works because of the `require`s.

**Comment by cgarnier** [comment]
I was unable to make it works with `vite` bundler. So, I forked and ugly fixed to make it esm compliant and make my builds pass. I wont pr this because i m sure it s exactly what you dont want to do :D and it will probably break the SSR. I published my package there: https://github.com/cgarnier/graphiql/packages/898685 Maybe it could help someone else. I hope someone will have time to work on this point because it will be an issue with the "new super fast and cool bundlers of the hell".

**Comment by acao** [comment]
a PR would be welcome @cgarnier ! we had issues before getting it to build properly with webpack and the many bundlers we support

**Comment by acao** [comment]
@cgarnier the answer to this so that it supports SSR are dynamic imports (`await import`). if you can get them working properly with the examples that would be a welcome PR!

if you look in the 2.0 RFC i think we were successful with that there, but because we use modern react with hooks and suspense

**Comment by cgarnier** [comment]
Hey @acao , I made some try to make it works with dynamic import few month ago but I saw that it s a big work (for me) and i aborted. I dont have the time to work on it right now.

**Comment by acao** [comment]
@cgarnier thank you so much for trying! this is not an easy problem to solve for such a complex application that is consumed in so many different ways. the way we plan on rewriting for 2.0.0 will hopefully make this easier!

**Comment by cgarnier** [comment]
On which branch is it ?

**Comment by tot-ra** [comment]
also tried snowpack and faced same issue with require in codemirror :(
hope there will be such support in 2.x

**Comment by acao** [comment]
We wont even be using codemirror in 2.x, thus why most of the 2.x effort has been on monaco-graphql. There is an RFC in packages/ but will probably be rewritten

**Comment by acao** [comment]
We will be using React.lazy() and/or suspense in 2.0.0, so we should be able to count on dynamic imports for 2.0.0. We will more than likely dynamically import all of the browser-only editor monaco modules and `monaco-graphql` within a provider, so hopefully it will all be abstracted away behind hooks, and it will build effortlessly!

**Comment by acao** [comment]
there is a working fix for this in #2248 (see: cypress), but something is failing with our test mock? I hope to revisit it later today or this week

**Comment by acao** [comment]
@ggascoigne @cgarnier @tot-ra here is the canary release with this fix: `graphiql@1.7.3-canary-f4f47342.0`
