### ISSUE TITLE
Add a favicon to prevent recurrent GET /favicon.ico on Chrome

### ISSUE THREAD

**Issue by sfbaltaci** [graphql/graphiql#161]
Hi,

first, I love GraphiQL 👍 

We should add a favicon (even a blank one) or an HTML fix to prevent Google Chrome and others browsers to constantly sending a request to get it.

It it pollutes logs 

<img width="142" alt="screen shot 2016-08-14 at 1 20 57 pm" src="https://cloud.githubusercontent.com/assets/1495118/17651730/f957ef8a-6221-11e6-98fd-4d44e512bdde.png">

**Comment by leebyron** [comment]
I'm going to close this since GraphiQL itself is only a UI component and not responsible for handling web traffic.

This is a default behavior for browsers - to fix this you should add a `<link>` element to your page (above your use of GraphiQL) pointing to your favicon, or leverage the browser default and place a favicon at the root of your server.

**Comment by Vanuan** [comment]
> This is a default behavior for browsers - to fix this you should add a <link> element to your page

But GraphiQL UI is not my page. I can't change its source code from inside my application.

**Comment by Vanuan** [comment]
Wait, I confused with express-graphql. It's fixed there:
https://github.com/graphql/express-graphql/pull/273

**Comment by Vanuan** [comment]
Oh, no, still not fixed.
