### ISSUE TITLE
Ability to refetch the document(schema)

### ISSUE THREAD

**Issue by Naoto-Ida** [graphql/graphiql#162]
I currently have a token-based authentication system for our GraphQL API.
I've managed to add in a custom input field in the tab bar for the developers to put in a token.
When a token is supplied, it is given permission to query.

The problem is that the documents are not fetched again,
resulting in query results coming back (if you know the fields), but no documentation for it.

Is there a way to forcefully refetch the documentation(schema)?

**Comment by asiandrummer** [comment]
Hi @Naoto-Ida! Not sure if I understood your question - are you letting the introspection query to be executed before/when developers put in a token?

**Comment by Naoto-Ida** [comment]
@asiandrummer Thanks!

To get into the nitty-gritty, I have to endpoints on the server.
`/graphql` for a GraphQL implementation which checks for tokens.
`/graphiql` for GraphiQL which is accessible by anyone.

When setting up GraphiQL, I have the following code:

```js
class MyGraphiQL extends Component {
  constructor(props) {
    super(props)
    this.state = {
      fetcher: this.graphqlFetcher.bind(this)
    }
  }

  graphQLFetcher(graphQLParams) {
    var fetchURL = THE_GRAPHQL_ENDPOINT
    var request = new Request(fetchURL)
    var customHeaders = new Headers()
    customHeaders.append('Accept', 'application/json')
    customHeaders.append('Content-Type', 'application/json')
    if (this.state.key.length > 0) {
      customHeaders.append("Authorization", `token ${this.state.key}`)
    }

   const myInit = {
     method: 'POST',
     headers: customHeaders,
     body: JSON.stringify(graphQLParams),
     credentials: 'include'
  }

  return fetch(request, myInit)
    .then((response) => {
	return response.text()
    }).then((responseBody) => {
	try {
	  return JSON.parse(responseBody)
       } catch (error) {
         return responseBody
      }
   })
  }

  render() {
    <GraphiQL
      	fetcher={this.state.fetcher}
      >
      ...
      </GraphiQL>
  }
}
```

I have an `<input>` in the toolbar which accepts tokens.
Then I set the token by `this.setState({key: THE_KEY})`.
Then I'm able to do queries, but since the docs are only fetched on the initial page load,
I can't show the user the proper documentation.
Right now I just have the page reload with the token.

**Comment by asiandrummer** [comment]
@Naoto-Ida If I understand correctly, I don't think your code actually fetches the schema at all to power `GraphiQL`, and hence, the documentations. The schema is fetched using a fetcher via an introspection query in `componentDidMount`, and since the schema isn't getting fetched on the component mount state, the documentation, powered by the schema, does not appear. The introspection query we use can be found [here](https://github.com/graphql/graphiql/blob/master/src/utility/introspectionQueries.js). You can also check out the schema ensuring logic in `GraphiQL.js` to understand how we use these queries.

I think there are a couple of things you could try out to fix this:
- Fetch the schema using the introspection query independently and provide it as a prop to `GraphiQL`.
```js
<GraphiQL fetcher={this.state.fetcher} schema={this.state.schema} />
```
- Ask token before mounting `GraphiQL` so that the introspection query is sent to the fetcher/server appropriately.

**Comment by Naoto-Ida** [comment]
We've decided to basically build a page that just wraps GraphiQL and refresh the page with headers based the token they've selected.

**Comment by xuorig** [comment]
👋 

Sorry to revive this issue. I'm running into the same problem, where inputs in the toolbar can alter the schema used on the backend.

> Fetch the schema using the introspection query independently and provide it as a prop to GraphiQL

- In that case, while we're fetching the schema. `null` is probably being passed to `GraphiQL` which in turn will also try to fetch the schema. That would trigger a double network call and double render initially, right ?
- In addition, every time the change is triggered, the introspection is re-ran, but having no access to loading (unless you set schema back to null, which will trigger the double introspection again), it's hard to make it a nice experience.

> Ask token before mounting GraphiQL so that the introspection query is sent to the fetcher/server appropriately.

The problem here is similar to the first point. Every time a change is made, GraphiQL needs to be replaced by a loading animation for example. It'd be much pleasant to use the built in animations in GraphiQL, and keep it mounted.


Would it make sense to either:

  - Give access to a public method to re run the `fetcher` with the introspection query.
  - Provide a callback so that one could pass `schema: this.state.schema` (initially `null`).  When the schema is refetched, the callback provides the new value for the schema so that the parent can update it's state.
  - Other ideas ?

Curious on what you think @asiandrummer! Thanks 💌

**Comment by Naoto-Ida** [comment]
Just to add my opinions, but I think the second one would be great as then we could have different renderings for when the `schema` is null or not null.

Thank you for reviving this @xuorig. Although we resolved to reloading the page with the new input and closed this issue, it doesn't feel like an smooth experience to the users.

**Comment by asiandrummer** [comment]
Hey @xuorig - let me try answering your questions.
> In that case, while we're fetching the schema. null is probably being passed to GraphiQL which in turn will also try to fetch the schema. That would trigger a double network call and double render initially, right ?

`props.schema` may take in 3 options: `null`, `undefined`, and an GraphQL schema. `undefined` (which is same as not passing in a prop) will send an introspection query, but `null` will just act as no-op, so there won't be another network call going out.

For rendering the components again, wouldn't that be what you'd want if you're making changes to the current schema? I'm not sure how you're making changes to the schema from the toolbar, but another option for loading indication is to use toolbar/footer to show the notification to users that a new schema is loading.

**Comment by xuorig** [comment]
> props.schema may take in 3 options: null, undefined, and an GraphQL schema. undefined (which is same as not passing in a prop) will send an introspection query, but null will just act as no-op, so there won't be another network call going out.

Awesome, did not realise!

> For rendering the components again, wouldn't that be what you'd want if you're making changes to the current schema? I'm not sure how you're making changes to the schema from the toolbar, but another option for loading indication is to use toolbar/footer to show the notification to users that a new schema is loading.

I decided to go with a footer notification for now. Would it make sense to expose `isWaitingForResponse` or at least a `fetching` prop to user land ?

Thanks again :dancing_men:
