### ISSUE TITLE
Support more customization options? 

### ISSUE THREAD

**Issue by blacksider** [graphql/graphiql#1620]
Currently ***graphiql*** only support several view customization options(children: Logo, ToolBar, Menu,...etc),  but I can't find a direct way to hide or show some elements, such as the whole toolbar, the resultviewer, or the docs panel, it would be great if there are options to control the ***visibility*** of some elements, and change the ***style*** of those elements.
Thanks!

**Comment by lasmil** [comment]
+1

**Comment by thomasheyenbrock** [comment]
With the release of `graphiql@2` last year, we also published a new package called `@graphiql/react`. This new package solves this issue, but not quite in the expected way. Let me explain.

Building in more customization options into GraphiQL would ever increase the API surface and maintenance complexity, which isn't something we wanted to do. Instead, GraphiQL is what we call the "**reference implementation for a GraphQL IDE**". It's merely using all the building blocks from `@graphiql/react` and sticks them together in a particular way.

If you want to customize GraphiQL, you have several options. Instead of reciting them here, here's a [link](https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md#customize) to the section of the README that goes into more detail. If these customization options do not solve your use-case, we encourage you to take the `GraphiQL` component as a template, create your own component and customize it to your needs.

As a final note, there might be things (state, UI components, ...) that are not exposed yet through `@graphiql/react`. If you find something that you'd need, feel free to open a new issue specifically for that thing.
