### ISSUE TITLE
LSP server broken when using stream method

### ISSUE THREAD

**Issue by rchl** [graphql/graphiql#1708]
Run server with:
```
./node_modules/graphql-language-service-cli/bin/graphql.js server --method stream
```
and send the `initialize` message to it.

The server will just crash in a non-crashy way (just exit with 0 exit code).

This issue was introduced by https://github.com/graphql/graphiql/pull/1651/files where it has changed the logger to post to `stdout` for non-Error messages:
```js
const processSt = severity === DIAGNOSTIC_SEVERITY.Error ? process.stderr : process.stdout;
```

This doesn't work for `stream` method as `stdio` is reserved for communicating with the LSP client.

@acao

**Comment by acao** [comment]
thanks for looking into this! excellent deduction as well. would you like to open a PR that ensures this works for streams? you should be able to pass the options down to Logger readily since it's instantiated in `createServer`, and then change the logic you referenced. When developing `yarn watch` to set the build watcher for language server/etc, and then you can just directly execute the cli bin path to test after every change, since yarn workspace takes care of all the local interdepdent resolutions. I won't have time to get to this for a while

since our tests and my manual testing is always with `ipc`, i've probably let the stream interface languish, my bad!

**Comment by rchl** [comment]
Thanks for providing helpful information. I might take a stab at it.
