### ISSUE TITLE
Store query in in browser local or session storage instead of url query param

### ISSUE THREAD

**Issue by joslarson** [graphql/graphiql#173]
Can we have the query saved in local/session storage instead of the url? If you kept it in browser storage you could even implement it in a way that it stores a limited history of previously run queries that the user could browse through. And if it's really needed, then we could even still support the query param for the purposes of linking to a query and have a share button.

**Note:** I feel like there must be a good reason for this, or it wouldn't be this way, but I tried searching for previous issues on the topic and found nothing so far, so I'm submitting this. Sorry if this has already been resolved.

**Comment by asiandrummer** [comment]
Hey @joslarson! We're using a local storage to store the query/variable strings. In fact, you can also customize this by providing your own means for a storage - [check this out](https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L66) for more details.

The URL with query string embedded is just for the purpose of the example. We're doing the embedding at [`index.html`](https://github.com/graphql/graphiql/blob/master/example/index.html#L45).

**Comment by joslarson** [comment]
Okay, interesting, thanks. I'm noticing most open/public graphql api's are setting up graphql this way (with the url storing the query as well), but it seems to me to be slowing down the editor once the queries get too long, and I'm just wondering why they are choosing to set it up that way, is that the default behaviour? And is there any reason not to set this feature up to only url escape the query into a query string when you want to share it as a link?

**Comment by asiandrummer** [comment]
As far as `GraphiQL` is concerned, the only default behavior is to use `localStorage` when no other storage means are provided. I'm guessing other public `GraphiQL` instance are using [`express-graphql`](https://github.com/graphql/express-graphql) library to fire up a `GraphiQL` instance in a quick and easy way, and [this code](https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js#L72-L78) includes the logic to embed query string to the URL, which is why you're seeing this behavior.

**Comment by joslarson** [comment]
@asiandrummer Ah, I see, thanks for responding. Feel free to close this.

**Comment by asiandrummer** [comment]
@joslarson feel free to talk to us with any other issues!
