### ISSUE TITLE
Render HTML responses

### ISSUE THREAD

**Issue by devknoll** [graphql/graphiql#18]
There's no real feedback if a server responds with something other than a 200 with correct query data.

It would be awesome if GraphiQL could either render the server response directly (using an iframe with HTML5 [`srcdoc`](http://caniuse.com/#feat=iframe-srcdoc)), or provide a hook to do so manually.

**Comment by leebyron** [comment]
Could you give me more info about the use-case? What is the case when a GraphQL endpoint return HTML?

**Comment by devknoll** [comment]
Ah, right, sorry. I'm specifically thinking for development. Seems also possible that proxy/network (think Cloudflare) errors might cause an occasional non-JSON response.

At the very least, some indication that it tried to run the query and something failed might be nice.

**Comment by gre** [comment]
I guess GraphQL could print somewhere (in footer bar) the status of the last call to the fetcher. If fetcher returns a failure (or the result is not a json) we could print an error message somewhere

**Comment by jimthedev** [comment]
I have a use-case for this but perhaps it is too specific to express-graphql and graphiql. Consider you've got a server that requires a login before getting to the Graphiql UI.  To accomplish this you've got an array of middleware passed to a custom express route. Your auth middleware comes first and performs an auth session check. Graphql-express is the second middleware in the array. Let's assume for these purposes that this is because you only want Graphiql to be available to staff or a developer group. If the currently logged in user has a session timeout occur while they are using Graphiql then chances are you're either going to return a login form (html) or something like a 403 Forbidden / Access Denied. Currently if you return html then Graphiql actually chokes on parsing, but if instead you return a 403 then it does nothing and errors to the console. 

In my case I'd ideally like to be able able to define a mapping of http codes to redirects or at least define a set of errors to display to the user in certain scenarios.

**Comment by jimthedev** [comment]
Looks like returning a string or json will work for my case, I'll just instruct users to log back in. Would be great to be able to provide a link, but alas, security. :)
