### ISSUE TITLE
[graphql-language-service] Relay __id Fields are Unknown

### ISSUE THREAD

**Issue by azz** [graphql/graphiql#2159]
Relay's client automatically defines an [`__id`](https://relay.dev/docs/guided-tour/list-data/updating-connections/#accessing-connections-using-__id) on any field-types which are queried with the `@connection` directive. E.g.:

```graphql
{
  things @connection(key: "things") {
    __id
  }
}
``` 

This `__id` is not part of the server schema, and thus currently trips the [`FieldsOnCorrectType`](https://github.com/graphql/graphql-js/blob/main/src/validation/rules/FieldsOnCorrectTypeRule.ts) rule. 

I've been trying to determine a way to ignore this, write a custom validation, etc., but I've come up short.

Any ideas? I'm coming from `vscode-graphql` if that's relevant.

**Comment by acao** [comment]
Great question! Custom validation has worked in the language server since well before my time!

### For `graphql-language-service-server`, `vscode-graphql` and any other IDE mode that uses the LSP server:

This readme needs another anchor for this section, but the second snippet is an example that shows how to add custom validation rules:

https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-server#custom-startserver

Because it requires an inline require, it needs to be a programattic config, only .js and .ts are supported currently. It predates dynamic imports

```ts

export default {
  schema: './schema.graphql',
  extensions:  {
  	 endpoints: { default: 'https://localhost:8080' },
     customValidationRules: require('./config/customValidationRules')
   }
}

```

here's where the config is actually loaded:

https://github.com/graphql/graphiql/blob/df57cd2556302d6aa5dd140e7bee3f7bdab4deb1/packages/graphql-language-service-interface/src/GraphQLLanguageService.ts#L201

this just expects a function that returns `ValidationRule[]` with the config as an argument, easy peasy!

### for graphiql

you can use the `validationRules` prop
