### ISSUE TITLE
Use flexbox standard syntax

### ISSUE THREAD

**Issue by guzgarcia** [graphql/graphiql#250]
It seems you guys have forgotten to place `display: flex` in the css classes.

This is the look under Firefox 45.x with default styles:

![](https://i.imgur.com/6DclS6T.png)

After add `display: flex`:

![](https://i.imgur.com/tDsMLBn.png)

**Comment by wincent** [comment]
Thanks for the report! I couldn't repro this on Firefox 49 or 50 (didn't have access to 45), so I downloaded v45 and I can repro.

I suspect most people allow the auto-updater to keep them on a more recent version, but v45 is still pretty recent (April 2016, I think), and the cost of fixing the issue seems low, so we may as well do it.
