### ISSUE TITLE
GraphiQL Sidebar Styles

### ISSUE THREAD

**Issue by noahsb** [graphql/graphiql#2777]
I'm using GraphiQL with the [Mantine](https://mantine.dev/) component library. When I render GraphiQL, the sidebar buttons aren't visible and the other buttons are significantly smaller:

<img width="1792" alt="Screen Shot 2022-09-25 at 6 48 25 PM" src="https://user-images.githubusercontent.com/49932437/192171090-0b551236-12dd-41ee-ae9f-2c80665ad715.png">

I believe this is an issue with how/when the styling is applied. This works fine when I create a new create react app without a component library.

Example code:

```
<MantineProvider withNormalizeCss withGlobalStyles>
  <GraphiQL fetcher={fetcher} />
</MantineProvider>
```

This only applies with graphiql@v2.0^

**Comment by jonathanawesome** [comment]
If you could stand up a reproduction that'd be super helpful.

**Comment by noahsb** [comment]
Sure thing! Here's a simple repo with the reproduction:

https://github.com/noahsb/graphiql-mantine-v2

**Comment by jonathanawesome** [comment]
Thanks for the repro. Looks like Mantine is using the very common `box-sizing` reset via the `withGlobalStyles` prop. The quick solution is to _not_ use that prop. Here's the related [Mantine docs page](https://mantine.dev/theming/mantine-provider/#css-reset-and-global-styles), though it's actually kind of confusing because 1) it doesn't mention the box-sizing reset in the list of styles added ([here's the source](https://github.com/mantinedev/mantine/blob/14a3ff014b0f339fe1f1d329c95193c7a358b414/src/mantine-styles/src/theme/GlobalStyles.tsx#L9)) and 2) you'd think this reset would be part of the `withNormalizeCSS` prop rather than the `withGlobalStyles`. 

@thomasheyenbrock, how do you feel about adding a light reset to the `@graphiql/react` root css file? I think it would improve the overall compatibility of the package.

**Comment by noahsb** [comment]
Thanks for the great explanation. Would definitely help my team to have a light reset of the css file, but will plan on removing the `withGlobalStyles` or using a version below 2.0 in the meantime. Thank you!

**Comment by thomasheyenbrock** [comment]
@jonathanawesome having a light reset that is scoped to the container element where we render GraphiQL sounds good to me 👍
