### ISSUE TITLE
[graphiql] Theme default override (e.g. Light instead of System)

### ISSUE THREAD

**Issue by klebba** [graphql/graphiql#2924]
GraphiQL now provides users with a way to select a theme: `System | Light | Dark` — the option is persisted, in my case using their browser's local storage in a k:v like `'graphiql:theme', 'light'`

It would be useful if GraphiQL would offer developers a way to choose the default theme, otherwise the GraphiQL UX may be incongruent with the surrounding application. In my case I have to override GraphiQL's behavior like this:

```
// Default the theme to 'light' to match the application style
const storedTheme = localStorage.getItem('graphiql:theme');
if (!storedTheme) {
   localStorage.setItem('graphiql:theme', 'light');
}
```

However the problem with this approach is that GraphiQL does not explicitly record `'graphiql:theme', 'system'` when a user makes this selection. Thus it is impossible to determine the difference between a user's first-run and their deliberate choice to use the system default.

Given that the constructor accepts `editorTheme` it is both confusing and unexpected that `theme` can't be configured in the same manner. Perhaps I'm missing something obvious?! Thanks in advance, Casey

**Comment by jonathanawesome** [comment]
The `useTheme` hook, which would allow you to set the theme when your app loads, is available from `@graphiql/react`...this could get you a quick fix while we work on a more long term solution. [Here's a sandbox](https://codesandbox.io/s/graphiql-usetheme-d6hnuy?file=/src/App.tsx).

Without understanding more about your app, it sounds like your ideal solution would be to expose a "defaultTheme" prop on the GraphiQL component. Would you also then want to disable the theme selector in the setting dialog so that your own app could handle the theme state?

**Comment by sdabhi23** [comment]
@jonathanawesome I can help out with this issue, it does not look very complex

**Comment by acao** [comment]
@sdabhi23 please, feel free to open a PR!

**Comment by dimaMachina** [comment]
Available in https://github.com/graphql/graphiql/releases/tag/graphiql%403.7.0with `defaulTheme` option
