### ISSUE TITLE
eslint tooling changes lead to obtuse errors

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3311]
After the eslint tooling changes, I'm seeing some obscure errors that don't even indicate what file is the problem
![image](https://github.com/graphql/graphiql/assets/1368727/3d2f5ed6-1051-4bdd-872f-762753b7635a)

following docs and similar bugs reported, this seems to indicate that our eslint config and prettier config are out of sync/clashing. prettier --write should fix this issue but does not. it is likely caused by a file that eslint is checking but is ignored by prettier

**Comment by acao** [comment]
I have seen this a few times, I will come back with a case to re-create it.

offhand, I think that for example pushing an import in a file with double quotes that is ignored by prettier will reproduce this issue

**Comment by B2o5T** [comment]
I made setup ESLint rule `quotes` to avoid unnecessary backticks https://github.com/graphql/graphiql/pull/3196
this rule matches Prettier, but also replaces backticks with single quotes

to remove console warning we should remove this script  https://github.com/graphql/graphiql/blob/ab387abca9891b7e27ec16adc7c2c3f76b8a2122/package.json#L62 because we already use `eslint-config-prettier` as last item in `extends` to disable all `style` rules except `quotes` https://github.com/graphql/graphiql/blob/ab387abca9891b7e27ec16adc7c2c3f76b8a2122/.eslintrc.js#L42-L51
