### ISSUE TITLE
GraphiQL should be flowtyped

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphiql#382]

**Comment by Zyst** [comment]
Do you guys have a (FB?) Style guide or something of the sort for flow types?

Not necessarily picking this up, but some additional info would be great.

**Comment by AGS-** [comment]
@Zyst, I think just in general using the built in types flow has would be more than enough. Here are some simple [examples](https://flowtype.org/docs/five-simple-examples.html) and in a broader sense [these](https://flowtype.org/docs/builtins.html) are the built in types.

**Comment by AGS-** [comment]
@Zyst also, this is a good example of [using flow inside React](https://flowtype.org/docs/react.html)

**Comment by Zyst** [comment]
Alright, I'm playing with Vim on the weekend so I'll try to get a PR done tomorrow.

**Comment by AGS-** [comment]
I definitely still want to work on this, I've just been a little busy with my ramp up

**Comment by wincent** [comment]
@AGS- Don't get too distracted. Oculus needs you!

**Comment by AGS-** [comment]
@wincent haha it's still a fun project to work on during weekends.

**Comment by AGS-** [comment]
@wincent also the stuff I do on Oculus is very close knitted with GraphiQL and Relay being awesome.

**Comment by wincent** [comment]
![dumbledore](https://user-images.githubusercontent.com/7074/28329513-f3cc3fbc-6b9e-11e7-87a8-7dcf2c524a15.png)

**Comment by asiandrummer** [comment]
@AGS- 👍

**Comment by acao** [comment]
We ended up exporting typescript types in the end. Though not statistically valid, [state of js](https://2020.stateofjs.com/en-US/technologies/javascript-flavors/) is representative enough to go off of to make this choice, and to choose not to support flow types for `GraphiQL`. Apparently flow's popularity is similar to coffeescript now :/

It makes me sad really, because of any type system, flow is still the truest to the vision of esnext, and always felt the most natural to javascript development. Typescript caught on to this eventually and did their best to adopt that approach, but there are just some aspects of the typescript inference engine that don't feel as powerful. I especially noticed this whilst converting the LSP modules.

We have flow types for other modules for legacy support but those will be deprecated soon. If anyone wants flow types for GraphiQL still, they can open a new issue :)
