### ISSUE TITLE
Mutation only works in GraphiQL

### ISSUE THREAD

**Issue by jeanpaulversace** [graphql/graphiql#415]
The following request works when I post the mutation from GraphiQL but does not work from the client-side of my app. 

I get a "POST http://localhost:3001/graphql 400 (Bad Request)" error in the console.

```
    const post = {
      userId: store.user.id,
      imageURLs: store.post.request.aws.imageURLs,
      tags: store.post.tags,
      link: store.post.link,
    };

    const query = `mutation CreatePost($post: PostInput) {
      createPost(post: $post) {
        user,
        tags,
        imageURLs,
        link
      }
    }`;

    return fetch('/graphql', {
      method: 'post',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query,
        variables: {
          post,
        },
      }),
      credentials: 'include',
    })
```

Does anyone know what is going on?

**Comment by asiandrummer** [comment]
@jeanpaulversace not sure what's going on here - 400 usually means the server doesn't understand the data. Is your server expecting the format of the body you're sending with the request?

**Comment by akomm** [comment]
Is the response body empty?

**Comment by Tzinov15** [comment]
Has this been resolved? I have the **exact** same issue. Works via GraphiQL, copy-paste to client code, returns with 400

**Comment by wincent** [comment]
@jeanpaulversace, @Tzinov15: Can you provide some more information about your server? ie. what packages/stack are you using to run the GraphQL endpoint?

As @asiandrummer said, a 400 indicates a bad request, so it would be interesting to see the request body and headers for a GraphiQL-initiated request and a client-initiated request; the difference must lie in there.

**Comment by asiandrummer** [comment]
@jeanpaulversace @Tzinov15 as @wincent said, we need more information to help debug the issue, possibly the actual request body and/or the server setup/hookup with the client.

I'm going to close this issue due to inactivity, but please do reopen/comment on this issue with more information and we'll gladly reopen this!

**Comment by Tzinov15** [comment]
I'm leaving my solution / realization in debugging this in case anyone happens to run into the same problem (which I doubt will happen since what I did was quite stupid).

On my backend I had `bodyParser.json()` running which as per the [documentation](https://github.com/expressjs/body-parser#api) sets the `req.body` to `{}` if there is not a match between the content-type that is specified and the content-type of the incoming request. I then looked at my client code and realized I was using `new FormData()` to construct the body of the fetch request I was using. I assume it was `FormData` that was setting the `content-type` to `multipart/form-data` REGARDLESS of the fact I was setting the content-type separately with a header. Anyways, got rid of FormData and just the request body to `JSON.stringify(data)` and I was golden
