### ISSUE TITLE
"GraphiQL" name?

### ISSUE THREAD

**Issue by scf4** [graphql/graphiql#517]
I understand it's a play on the word graphical but it has the potential for a lot of confusion, particularly for those new to GraphQL.

I've personally seen a few people confused with https://github.com/apollographql/graphql-server because of its vars named `graphqlKoa` and `graphiqlKoa`, and it's far more difficult to find information about  Graph*i*QL on Google it than it needs to be. 

It even seems like GraphiQL itself has to italicize the *i* due to this. How many people have you heard say Graph-I-QL?

Curious to hear others opinions on this?

**Comment by wincent** [comment]
Thanks for posting, @scf4. It's definitely true that "GraphiQL" is visually — perhaps even audibly —
 quite close to "GraphQL" itself, but like you say, the play on words is quite intentional. As you probably understand, changing the project name isn't something that we'd consider practical at this time, so problems like the variable naming issue that you raised should really be solved locally within that project, either by picking other names, or using other means (code comments, code structure etc) to make things clear.

Google seems to have no trouble returning GraphiQL-related search results (even if it does ask "Did you mean: graphql"?). Are you suggesting that people may have difficulty typing the word, or that they may not even know what it is called? If the latter, what search terms would you expect people to use to find it? For me, "graphql ide" yields GraphiQL as the second result (and a project called, er, "graphql-ide", as the first) so that sounds about right.

> It even seems like GraphiQL itself has to italicize the `i` due to this

As far as I know this is just a playful stylistic choice and wasn't done because we "had" to.

I'm going to close this for now because it's not clear what actionable item you are proposing, and we'd like to keep the issue tracker for concrete bugs and issues which we can take action on. But if you have suggestions for specific steps that we could/should take within this repo, please file issues for those.
