### ISSUE TITLE
graphiql (0.11.2) web page doesn't show

### ISSUE THREAD

**Issue by xsq007** [graphql/graphiql#549]
graphiql doesn't work with version 0.11.2 because it uses http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js, which is corrupted (incomplete)

Fix the issue by modifying following line in express-graphql/dist/renderGraphiQL.js
// change from 0.10.1 to 0.10.2
`var GRAPHIQL_VERSION = '0.10.2';`

Not sure who should fix the file http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js.

**Comment by wincent** [comment]
@xsq007: We can't go back and modify prior releases.

- http://cdn.jsdelivr.net/graphiql/0.11.2/graphiql.min.js isn't the right URL;
- http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.min.js is.

This was fixed in https://github.com/graphql/express-graphql/commit/9007293b3138ef4180ab62ddcbd3f24e587171f1 — we just need to cut a new release of express-graphql, which I will do presently.
