### ISSUE TITLE
Why does auto-fill/complete fill in nullable fields?

### ISSUE THREAD

**Issue by ffxsam** [graphql/graphiql#552]
Given the following schema:

```graphql
  type Thing {
    name: String!
    size: Int
    dummy1: Boolean!
    dummy2: Boolean
  }

  type Query {
    things: [Thing]
  }
```

I type the following in GraphiQL:

```graphql
{
  things
}
```

And when I run the query, `things` expands:

```graphql
{
  things {
    size
    dummy2
  }
}
```

This strikes me as a bit odd. Why would the nullable fields populate, instead of the non-nullable ones?

**Comment by asiandrummer** [comment]
Hi @ffxsam - as you've observed, GraphiQL [automatically fills in leaf selections](https://github.com/graphql/graphiql/blob/master/src/utility/fillLeafs.js) because 
[the GraphQL specification validates against non-leaf-field selections.](http://facebook.github.io/graphql/#sec-Leaf-Field-Selections) GraphQL non-nulls are in fact a wrapper around GraphQL types, so the `name` and `dummy1` fields are really:
```
new GraphQLNonNull(new GraphQLScalarType('string'));
```
More info can be looked up [here](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L1242).

**Comment by svilendobrev** [comment]
the function getDefaultFieldNames uses isLeafType to guess fields to include, but that function does not see through into NonNull wrapped things (scalars).

This can be fixed easy, if in the function getDefaultFieldNames, the isLeafType is called on getNullableType( fields[fieldName].type ) instead of directly on fields[fieldName].type.

i could make a patch/PullReq but am not too fluent in javascript..

**Comment by asiandrummer** [comment]
The point of this feature is to create a minimal query structure just enough to be run and produce some sort of the results without failing obvious validation/lint errors, and filling non-null leave nodes is risky since it could possibly return with null value errors.

Closing this - lmk if you have more questions!
