### ISSUE TITLE
Title-bar is cut off due to hard coded height.

### ISSUE THREAD

**Issue by CarlRosell** [graphql/graphiql#571]
https://github.com/graphql/graphiql/blob/6c446a659c11dd2c81b7c75b3531c276746f35ba/css/doc-explorer.css#L9
This line sets the height to be 34px tall which will hide parts of the titles and add an overflow scroll behavior.

![aug-16-2017 13-09-24](https://user-images.githubusercontent.com/2036823/29362036-77a0c46e-828a-11e7-93e6-1f612325890c.gif)

Just by removing the height the problem goes away. I'm not that familiar with this entire codebase, but removing the height would not cause any other visual regression.

**Comment by CarlRosell** [comment]
Just found that this is only a problem when combined with `box-sizing: border-box;`.
Removing the explicit height will make the UI look the same with/without `box-sizing: border-box;`

**Comment by bdougie** [comment]
Hey friends, I was interested in contributing back to this project and spent some time trying to recreate this issue. I was, unfortunately, unable to reproduce on Safari, Chrome, or Firefox. I also tried on the Electron and can confirm the over scrolling does not appear. 

Perhaps it resolved unintentional through another improvement feature or bug fix. 

I know this is an old issue, but perhaps @CarlRosell can provide details on the environment in which this bug was produced. 

**Chrome:**
![Screenshot 2020-02-12 12 50 31](https://user-images.githubusercontent.com/5713670/74376055-4c5fc780-4d96-11ea-934c-01a8317be809.png)

**Firefox (Developer Edition):**
![Screenshot 2020-02-12 12 52 05](https://user-images.githubusercontent.com/5713670/74376153-7fa25680-4d96-11ea-9deb-618491a470f2.png)

**Safari:**
![Screenshot 2020-02-12 12 51 51](https://user-images.githubusercontent.com/5713670/74376124-71543a80-4d96-11ea-9930-31a678d55344.png)

**Electron:**
![Screenshot 2020-02-12 12 49 18](https://user-images.githubusercontent.com/5713670/74376105-626d8800-4d96-11ea-973a-d26c6aad06b4.png)

Aside, I am impressed with how Firefox treats responsive design.

(gif coming soon). 

## Next steps?
Let me know if there is anything else needed on this to reproduce, otherwise, I suggest closing the issue and labeling `wontfix` or `not reproducible`.

**Comment by acao** [comment]
hey @bdougie thanks for this! we are in the midst of implementing a re-design, so we will certainly factor this in for the new layout and components!  The offending css is going away anyways, and is about to be replaced with a theme-ui implementation, and a new layout for the documentation explorer.

if you're looking for something to help on, reach out on Discord and I can help you find something, but it's tricky now because we are in the midst of re-architecting so much!

**Comment by CarlRosell** [comment]
I had forgotten about this issue, and have not seen it since I reported it. I'll close this one and look forward to seeing what the re-design will look like 😄
