### ISSUE TITLE
Inline spread without type condition on non-null type gives an error

### ISSUE THREAD

**Issue by rmosolgo** [graphql/graphiql#584]
If you make an untyped spread on a non-null type, GraphiQL gives you a warning:

![image](https://user-images.githubusercontent.com/2231765/29774708-d0171ce8-8c02-11e7-984c-bfae472abbff.png)

Here's a reproduction of the bug: 

http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allFilms(first%3A%201)%20%7B%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20...%20%7B%0A%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=null

But I think this is OK, here's the spec: 

> If the TypeCondition is omitted, an inline fragment is considered to be of the same type as the enclosing context.

https://facebook.github.io/graphql/#sec-Inline-Fragments

Is this error correct? Should the server accept this query, or should it be rejected? 

cc @willianvdv who identified this

**Comment by asiandrummer** [comment]
Whoa, great catch! I'm not sure why [this code](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/PossibleFragmentSpreads.js#L45) returns a non-null version of the parent type instead of the same parent type  - cc @leebyron for this. I think this is a bug.

Also, this probably belongs in `graphql-js` - would it be okay if we move this issue there? Also would be super grateful if we can get a PR for the fix.

**Comment by acao** [comment]
@rmosolgo can you confirm this behavior is fixed in 0.17.0? we have https://graphiql-test.netlify.com if you'd like to give it a whirl. see if it's been fixed in graphql-js already?

**Comment by rmosolgo** [comment]
It looks like this has been fixed in the last 2 years 🎉 The example link above no longer demonstrates the error:

![image](https://user-images.githubusercontent.com/2231765/69966507-8aae5000-14e4-11ea-9f02-ae2291dd080e.png)
