### ISSUE TITLE
minify graphql

### ISSUE THREAD

**Issue by drmax24** [graphql/graphiql#585]
Hello! We are using your product in our company in pair with laravel-graphql
(https://github.com/Folkloreatelier/laravel-graphql)

We have a great pleasure!

However. Can you add a minify button to graphiql near to prettify button?
Our programmers use get queries based on graphiql url and share them with each other, however after you format query you need to minify it back manually or it will be %%%%%horrible-whitespace-uri-encoded%%%%%.

Please can you add a minify option

**Comment by AGS-** [comment]
Hi! This seems like a pretty niche use case so I don't think it's something we'll build in the foreseeable future. We're trying to keep built in features in graphiql as simple as possible. 

You can add this functionality in by adding a custom <GraphiQL.Button> into the toolbar. I'm going to go ahead and close this issue since it isn't something on our roadmap.

**Comment by drmax24** [comment]
How do you guys share graphql between multiple developers?

**Comment by asiandrummer** [comment]
@drmax24 I'm having troubles understanding what you need "minification" for sharing queries between developers. Is it solely because of the formatting of the URL?

In Facebook we have a number of solutions to share queries between developers. We use a URL shortener to create a shorter/simpler version of GraphiQL url with query as a URL parameter. We also have a classical "export" feature that allows people to save queries/variables/responses in some sort of a web document (imagine something similar to Gist). I'm not sure if you're familiar with a concept of "persisted queries" - that's another way that we can share a query amongst others, by providing a persisted query ID for others to load in the GraphiQL tool.

I'm not sure what your situation allows for, but my suggestion is to try one of the above ways instead of sharing a query using an URL param. Even with the URL shortener, queries and variables tend to get bigger in size, and you will hit the URL length limit per browser specifications.

**Comment by imolorhe** [comment]
@asiandrummer I think he's referring to the ability to minify a query to remove unnecessary whitespace and comments from it (I might be wrong though but that's how I understand it).

@drmax24 You can checkout https://github.com/imolorhe/altair if it helps.
