### ISSUE TITLE
Subscription error message

### ISSUE THREAD

**Issue by codepunkt** [graphql/graphiql#604]
When a subscription query is not formulated well and hits validation errors, the error display is slightly lackluster:

![subscription_error](https://user-images.githubusercontent.com/603683/30844046-383f7de2-a28d-11e7-9d54-ee9d0577a8a5.png)

![network_websockets](https://user-images.githubusercontent.com/603683/30844074-66c6aff0-a28d-11e7-9f38-f87a7f8d95f1.png)

Is this on anyones list? I'd assume a readable error message should be displayed the same way that it's done when sending malformed queries or mutations.

**Comment by asiandrummer** [comment]
@codepunkt it's not - I'm willing to tackle this myself unless someone wants to contribute. I'll try taking a look at this within a day or two, but it might take longer for me to get to it due to other responsibilities unfortunately. I'll tag this with Help Needed label for now in case someone's interested.

Thanks for filing an issue - this is a helpful bug report!

**Comment by codepunkt** [comment]
@asiandrummer Just wanted to let you guys know. Thank you!

**Comment by esseswann** [comment]
Is there any progress on resolving this? Debugging subscriptions through Network tab in Chrome Dev Tools is very painful

**Comment by acao** [comment]
resolved by #934 #936
