### ISSUE TITLE
How integrate this with another graphql server ? (eg: graphql-go server)

### ISSUE THREAD

**Issue by gushitong** [graphql/graphiql#640]
If I have a graphql-golang server running at: [http://localhost:8080](http://localhost:8080),
how can I config graphiql running with it ?

**Comment by pekjiaMIIIuK** [comment]
???
-------- Исходное сообщение --------От: gushitong <notifications@github.com> Дата: 11.12.17  14:04  (GMT+03:00) Кому: graphql/graphiql <graphiql@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [graphql/graphiql] How integrate this with another graphql server ?
  (eg: graphql-go server) (#640) 
If I have a graphql-golang server running at: http://localhost:8080,

how can I config graphial running with it ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/graphql/graphiql","title":"graphql/graphiql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/graphql/graphiql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How integrate this with another graphql server ? (eg: graphql-go server) (#640)"}],"action":{"name":"View Issue","url":"https://github.com/graphql/graphiql/issues/640"}}}

**Comment by gunsluo** [comment]
I have the same problem.
not sure if graphiql supports another graph server? if support, how to do it.

**Comment by timgilbert** [comment]
If you're just serving up a static index.html page, the easiest thing to do is modify the `fetch()` statement to point to your graphql server:

https://github.com/graphql/graphiql/blob/master/example/index.html#L112

**Comment by acao** [comment]
graphiql supports any graphql server, just see the readme and it will explain how to write a custom fetcher for your specific graphql implementation.
