### ISSUE TITLE
expose query result on global object

### ISSUE THREAD

**Issue by Janpot** [graphql/graphiql#686]
Would it be possible to add the query result to the global object?
That way I can use the browser devtools to further manipulate the result.

**Comment by thomasheyenbrock** [comment]
Hey @Janpot 👋 When you say "global object", are you referring to the instance of the `GraphiQL` class stored in `window.g`? This has been removed in `graphiql@2` since the `GraphiQL` component is no longer a class component and in general this pattern would not work when embedding GraphiQL into other applications where there could be multiple instances on a single page.

I'm gonna close this issue for now, feel free to come back to this if my assumption was incorrect and we can see if it makes sense to reopen this 🙏
