### ISSUE TITLE
not allowed to copy paste a "|" which unicode is \u007c

### ISSUE THREAD

**Issue by changedi** [graphql/graphiql#720]
When make a copy of a text like "abcdef|def" from other editor or browser , and then paste to the graphiQL's QueryEditor , the editor result only shows "abcdef  def" with whitespace instead of a '|' vertical line seprator.

**Comment by navdeep3** [comment]
Facing the same issue, cannot paste PIPE symbol. Do we have a work-around on this? How can I make "|" display on the query editor by pasting?

**Comment by benjie** [comment]
I believe this issue is fixed so am closing it; I can happily paste a pipe symbol from the text above into the QueryEditor.

@navdeep3 Please try and reproduce your issue on https://graphiql-test.netlify.com/ - if you can, then please request this issue gets reopened with additional details about your environment: browser, OS,etc. It would be great to get a copy of the error messages from the javascript console too.
