### ISSUE TITLE
Keyboard shortcut to add all fields

### ISSUE THREAD

**Issue by jimthedev** [graphql/graphiql#75]
There are times when I want to add all fields then remove some. I'd be fantastic l if there was a way to add all fields in a given navigation context using a keyboard shortcut.

**Comment by jimthedev** [comment]
Fantastic tool btw. Feel free to close this, just wanted to submit a potentially useful feature.

**Comment by asiandrummer** [comment]
@jimthedev We already have a feature that kinda does what you suggested - if, during an execution stage, a query is invalid due to the innermost field (terminal fields) not representing a leaf selection (http://facebook.github.io/graphql/#sec-Leaf-Field-Selections), GraphiQL will automatically fill in the leaf selections for invalid fields. Take a look at https://github.com/graphql/graphiql/blob/master/src/utility/fillLeafs.js and see if this is something you wanted.

If you meant recursively adding all non-terminal fields and terminal fields, you might end up in a situation where the field call added may address the top-level type, which ends up in an infinite loop of field completions.

**Comment by leebyron** [comment]
Closing this since it's aging and tricky to implement in a usable way. However anyone who stumbles here in the future - it would certainly be an interesting PR!

**Comment by sebastienfi** [comment]
Would love to have this

**Comment by acarl005** [comment]
Also, the automatic leaf-filling does not work within a fragment.

**Comment by acarl005** [comment]
@jimthedev I have a fork of GraphiQL where I added this feature. It adds all available field names (non-recursively) with <Alt-F> based on whichever field the cursor is inside of.

acarl005/graphsiql@9f88eba

**Comment by kirillgroshkov** [comment]
Would love to have it too!
Or any other way to do * for debugging. I understand that for production * shouldn't be used according to the intended use and the concept of GraphQL itself. But for debugging it's invaluable!

**Comment by imolorhe** [comment]
https://github.com/imolorhe/altair

**Comment by capaj** [comment]
@imolorhe why do link this here? Does altair have this feature? Because I just tried it out and it doesn't seem to have this feature.

**Comment by imolorhe** [comment]
@capaj Oh right! I confused the question for another 😅
