### ISSUE TITLE
What unit does graphql-language-service use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [graphql/graphiql#886]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by benjie** [comment]
I'm not familiar with the LSP, and don't know what "cluster indexes for LSP ranges" even means, but the GraphQL spec states UTF-8; so I think that's our vote on this (since no-one else replied).

https://graphql.github.io/graphql-spec/June2018/#sec-String

Hope this helps; I'm going to close this issue but let us know if you need more information.
