### ISSUE TITLE
Publish New Release of graphql-language-service-* packages

### ISSUE THREAD

**Issue by ganemone** [graphql/graphiql#927]
It would be awesome if we could get a new release of the `graphql-language-service-*` packages. Even if it is a prerelease or alpha version. Looks like the previous release was over a year ago.

**Comment by acao** [comment]
we are looking to do just that, was just getting ready for that in the coming weeks.
a big question was whether or not babel should be configured for `regeneratorRuntime` or not, with async/await being a factor in 2.0. I think we should use `node: true` so that its async/await by default, and folks can choose how to match each environment. Otherwise, with the current configuration (default `@babel/preset-env`), it will effectively downgrade the async/await to regeneratorRuntime, meant to be compatible with older browsers.

we will also need to bump everything a major version (to 2.0.x) that depends on gls-utils, which is everything gls except for gls-types. 
codemirror-graphql has already gone to 9.0, for the 2.0.x parser/interface upgrade

**Comment by ganemone** [comment]
I think if you would release a 2.0.0-alpha.0 version, it would unblock a lot of people without requiring you to 100% have all the exact details in order. Just an alpha release of the current state would be immensely helpful.

**Comment by acao** [comment]
https://github.com/graphql/graphiql/pull/941

**Comment by acao** [comment]
Done!
